name: Workflow with Event Filters
on: 
  push:
    branches:
      - main
      - feature/*
      - feature/**
    paths:
      - "temp.md"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "Step one"